bank/urls.py
from django.urls import path
from . import views


app_name = "bank"

urlpatterns = [
    path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),

    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),
]

kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bank.urls')),
]

bank/models.py
from __future__ import annotations
from decimal import Decimal
from django.conf import settings
from django.db import models, transaction
from django.db.models import Q
from django.db.models.query import QuerySet
from django.contrib.auth.models import User
from .errors import InsufficientFunds


class UID(models.Model):
    @classmethod
    @property
    def uid(cls):
        return cls.objects.create()

    def __str__(self):
        return f'{self.pk}'


class Rank(models.Model):
    name        = models.CharField(max_length=35, unique=True, db_index=True)
    value       = models.IntegerField(unique=True, db_index=True)

    @classmethod
    def default_rank(cls) -> Rank:
        return cls.objects.all().aggregate(models.Min('value'))['value__min']

    def __str__(self):
        return f'{self.value}:{self.name}'


class Customer(models.Model):
    user        = models.OneToOneField(User, primary_key=True, on_delete=models.PROTECT)
    rank        = models.ForeignKey(Rank, default=2, on_delete=models.PROTECT)
    personal_id = models.IntegerField(db_index=True)
    phone       = models.CharField(max_length=35, db_index=True)

    @property
    def full_name(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'

    @property
    def accounts(self) -> QuerySet:
        return Account.objects.filter(user=self.user)

    @property
    def can_make_loan(self) -> bool:
        return self.rank.value >= settings.CUSTOMER_RANK_LOAN

    @property
    def default_account(self) -> Account:
        return Account.objects.filter(user=self.user).first()

    def make_loan(self, amount, name):
        assert self.can_make_loan, 'User rank does not allow for making loans.'
        assert amount >= 0, 'Negative amount not allowed for loan.'
        loan = Account.objects.create(user=self.user, name=f'Loan: {name}')
        Ledger.transfer(
            amount,
            loan,
            f'Loan paid out to account {self.default_account}',
            self.default_account,
            f'Credit from loan {loan.pk}: {loan.name}',
            is_loan=True
        )

    @classmethod
    def search(cls, search_term):
        return cls.objects.filter(
            Q(user__username__contains=search_term)   |
            Q(user__first_name__contains=search_term) |
            Q(user__last_name__contains=search_term)  |
            Q(user__email__contains=search_term)      |
            Q(personal_id__contains=search_term)      |
            Q(phone__contains=search_term)
        )[:15]

    def __str__(self):
        return f'{self.personal_id}: {self.full_name}'


class Account(models.Model):
    user        = models.ForeignKey(User, on_delete=models.PROTECT)
    name        = models.CharField(max_length=50, db_index=True)

    class Meta:
        get_latest_by = 'pk'

    @property
    def movements(self) -> QuerySet:
        return Ledger.objects.filter(account=self)

    @property
    def balance(self) -> Decimal:
        return self.movements.aggregate(models.Sum('amount'))['amount__sum'] or Decimal(0)

    def __str__(self):
        return f'{self.pk} :: {self.user} :: {self.name}'


class Ledger(models.Model):
    account     = models.ForeignKey(Account, on_delete=models.PROTECT)
    transaction = models.ForeignKey(UID, on_delete=models.PROTECT)
    amount      = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp   = models.DateTimeField(auto_now_add=True, db_index=True)
    text        = models.TextField()

    @classmethod
    def transfer(cls, amount, debit_account, debit_text, credit_account, credit_text, is_loan=False) -> int:
        assert amount >= 0, 'Negative amount not allowed for transfer.'
        with transaction.atomic():
            if debit_account.balance >= amount or is_loan:
                uid = UID.uid
                cls(amount=-amount, transaction=uid, account=debit_account, text=debit_text).save()
                cls(amount=amount, transaction=uid, account=credit_account, text=credit_text).save()
            else:
                raise InsufficientFunds
        return uid

    def __str__(self):
        return f'{self.amount} :: {self.transaction} :: {self.timestamp} :: {self.account} :: {self.text}'

bank/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Customer, Account


class TransferForm(forms.Form):
    amount  = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(['Username already exists.'])
        return self.cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('rank', 'personal_id', 'phone')


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)

bank/views.py
from decimal import Decimal
from secrets import token_urlsafe
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from .forms import TransferForm, UserForm, CustomerForm, NewUserForm, NewAccountForm
from .models import Account, Ledger, Customer
from .errors import InsufficientFunds


@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank:staff_dashboard'))
    else:
        return HttpResponseRedirect(reverse('bank:dashboard'))


# Customer views

@login_required
def dashboard(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank/dashboard.html', context)


@login_required
def account_details(request, pk):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    account = get_object_or_404(Account, user=request.user, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank/account_details.html', context)


@login_required
def transaction_details(request, transaction):
    movements = Ledger.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'bank/transaction_details.html', context)


@login_required
def make_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = Account.objects.get(pk=form.cleaned_data['credit_account'])
            credit_text = form.cleaned_data['credit_text']
            try:
                transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank/error.html', context)
    else:
        form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts
    context = {
        'form': form,
    }
    return render(request, 'bank/make_transfer.html', context)


@login_required
def make_loan(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if not request.user.customer.can_make_loan:
        context = {
            'title': 'Create Loan Error',
            'error': 'Loan could not be completed.'
        }
        return render(request, 'bank/error.html', context)
    if request.method == 'POST':
        request.user.customer.make_loan(Decimal(request.POST['amount']), request.POST['name'])
        return HttpResponseRedirect(reverse('bank:dashboard'))
    return render(request, 'bank/make_loan.html', {})


# Staff views

@login_required
def staff_dashboard(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    return render(request, 'bank/staff_dashboard.html')


@login_required
def staff_search_partial(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    search_term = request.POST['search_term']
    customers = Customer.search(search_term)
    context = {
        'customers': customers,
    }
    return render(request, 'bank/staff_search_partial.html', context)


@login_required
def staff_customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=customer.user)
        customer_form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        user_form = UserForm(request.POST, instance=customer.user)
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    new_account_form = NewAccountForm()
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'new_account_form': new_account_form,
    }
    return render(request, 'bank/staff_customer_details.html', context)


@login_required
def staff_account_list_partial(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank/staff_account_list_partial.html', context)


@login_required
def staff_account_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    account = get_object_or_404(Account, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank/account_details.html', context)


@login_required
def staff_new_account_partial(request, user):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_account_form = NewAccountForm(request.POST)
        if new_account_form.is_valid():
            Account.objects.create(user=User.objects.get(pk=user), name=new_account_form.cleaned_data['name'])
    return HttpResponseRedirect(reverse('bank:staff_customer_details', args=(user,)))


@login_required
def staff_new_customer(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_user_form = NewUserForm(request.POST)
        customer_form = CustomerForm(request.POST)
        if new_user_form.is_valid() and customer_form.is_valid():
            username    = new_user_form.cleaned_data['username']
            first_name  = new_user_form.cleaned_data['first_name']
            last_name   = new_user_form.cleaned_data['last_name']
            email       = new_user_form.cleaned_data['email']
            password    = token_urlsafe(16)
            rank        = customer_form.cleaned_data['rank']
            personal_id = customer_form.cleaned_data['personal_id']
            phone       = customer_form.cleaned_data['phone']
            try:
                user = User.objects.create_user(
                        username=username,
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                )
                print(f'********** Username: {username} -- Password: {password}')
                Customer.objects.create(user=user, rank=rank, personal_id=personal_id, phone=phone)
                return staff_customer_details(request, user.pk)
            except IntegrityError:
                context = {
                    'title': 'Database Error',
                    'error': 'User could not be created.'
                }
                return render(request, 'bank/error.html', context)
    else:
        new_user_form = NewUserForm()
        customer_form = CustomerForm()
    context = {
        'new_user_form': new_user_form,
        'customer_form': customer_form,
    }
    return render(request, 'bank/staff_new_customer.html', context)

bank/templates/bank/account_details.html
{% extends "base.html" %}

{% block main %}

{% if user.is_staff %}
<p>Welcome, {{ user }}.</p>
{% else %}
<p>Welcome, {{ user.customer.full_name }}.</p>
{% endif %}

<h3>Account Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
        <th>Balance</th>
    </tr>
    <tr>
        <td>{{ account.pk }}</td>
        <td>{{ account.name }}</td>
        <td class="amount">{{ account.balance|floatformat:"2" }}</td>
    </tr>
</table>

<h3>Account Transactions</h3>

<table>
    <tr>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in account.movements %}
    <tr>
        <td><a href="{% url 'bank:transaction_details' movement.transaction %}">{{ movement.transaction }}</a></td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank/templates/bank/dashboard.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>My accounts:</h3>
<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank:account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock main %}

bank/templates/bank/error.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customer.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock main %}

bank/templates/bank/make_loan.html
{% extends "base.html" %}

{% block main %}
<form action="{% url 'bank:make_loan' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <label>
        Name for loan
        <input name="name" type="text" />
    </label>
    <label>
        Amount
        <input name="amount" />
    </label>
    <button>Submit</button>
    </fieldset>
</form>
{% endblock main %}

bank/templates/bank/make_transfer.html
{% extends "base.html" %}

{% block main %}
<form action="{% url 'bank:make_transfer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ form }}
    <button>Log In</button>
    </fieldset>
</form>
{% endblock main %}

bank/templates/bank/staff_account_list_partial.html
<tbody id="account-list">
{% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
        <td>{{ account.balance|floatformat:"2" }}</td>
    </tr>
{% endfor %}
</tbody>

bank/templates/bank/staff_customer_details.html
{% extends "base.html" %}

{% block main %}

<h3>Customer Details</h3>

<form action="{% url 'bank:staff_customer_details' customer.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
    <button>Update User</button>
    </fieldset>
</form>

<table>
    <thead>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Account Balance</th>
        </tr>
    </thead>
    <tbody
        id="account-list"
        hx-swap="outerHTML"
        hx-get="{% url 'bank:staff_account_list_partial' customer.pk %}"
        hx-trigger="load">
    </tbody>
</table>

<h3>Create New Account</h3>
<form action="{% url 'bank:staff_new_account_partial' customer.user.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_account_form.as_p }}
    <button>Create Account</button>
    </fieldset>
</form>

{% endblock main %}

bank/templates/bank/staff_dashboard.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user }}.</p>

<fieldset>
    <label>Customer Look Up</label>
    <input name="search_term"
           placeholder="Search on customer data"
           class="form-control"
           type="text"
           hx-post="{% url 'bank:staff_search_partial' %}"
           hx-trigger="keyup changed delay:500ms"
           hx-target="#search-results"
           hx-indicator=".htmx-indicator"
    />
    {% csrf_token %}
</fieldset>

<table>
    <thead>
        <th>ID</th>
        <th>Persal ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
    </thead>
    <tbody id="search-results">
    </tbody>
</table>

{% endblock main %}

bank/templates/bank/staff_new_customer.html
{% extends "base.html" %}

{% block main %}
<form action="{% url 'bank:staff_new_customer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_user_form }}
        {{ customer_form }}
    <button>Create User</button>
    </fieldset>
</form>
{% endblock main %}

bank/templates/bank/staff_search_partial.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank:staff_customer_details' customer.pk %}">{{ customer.pk }}</a></td>
    <td>{{ customer.personal_id }}</td>
    <td>{{ customer.full_name }}</td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
</tr>
{% endfor %}

bank/templates/bank/transaction_details.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>Transaction Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Transaction UID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in movements %}
    <tr>
        <td>{{ movement.account }}</td>
        <td>{{ movement.transaction }}</td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}