bank/urls.py
from django.urls import path
from . import views


app_name = "bank"

urlpatterns = [
    path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),

    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),
]

kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bank.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'holiday.css' %}" media="screen" />
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" media="screen" />
    <title>KEA Bank</title>
</head>
<body>

    {% load l10n %}

    <header>
        <h1>KEA Bank</h1>
        {% if user.is_staff %}
        <h2>Bank Staff Portal</h2>
        {% else %}
        <h2>Bank Customer Portal</h2>
        {% endif %}
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'bank:index' %}">Home</a></li>
            <li>
                <span>Menu</span>
                <ul>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}">Django Admin</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                </ul>
            </li>
            {% if user.is_staff %}
            <li><a href="{% url 'bank:staff_new_customer' %}">New Customer</a></li>
            {% else %}
            <li><a href="{% url 'bank:make_transfer' %}">Make Transfer</a></li>
            <li><a href="{% url 'bank:make_loan' %}">Make Loan</a></li>
            {% endif %}
        </ul>
    </nav>

    <main>
    {% block main %}
    {% endblock main %}
    </main>

    <footer>
        <p>&copy; 2021 Fat Cats Corp.</p>
    </footer>
    <script src="https://unpkg.com/htmx.org@1.5.0" integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI" crossorigin="anonymous"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>
</html>